-- =============================================================================
-- Migration: 0036 - Digital Class Logbook & Conduct Evaluation System
-- Phase: Homeroom Teacher Hub, TT22 Conduct, AI Report Card Comments
-- Created: 2026-09-25
-- =============================================================================
-- This migration implements:
-- 1. Digital Class Logbook (Sổ Đầu Bài Điện Tử) for daily lesson tracking
-- 2. Student Conduct Evaluations (Đánh giá Hạnh kiểm TT22) per semester
-- 3. Class Discipline Records for class monitor tracking (Nề nếp & Thi đua)
-- =============================================================================

-- =============================================================================
-- DIGITAL CLASS LOGBOOKS TABLE
-- Records daily lesson entries by teachers with attendance and lesson ratings
-- =============================================================================
CREATE TABLE IF NOT EXISTS digital_class_logbooks (
  id VARCHAR(64) PRIMARY KEY,
  school_id VARCHAR(64) NOT NULL,
  class_id VARCHAR(64) NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  academic_year VARCHAR(32) NOT NULL,
  semester INTEGER NOT NULL CHECK (semester IN (1, 2)),
  
  -- Lesson info
  date DATE NOT NULL,
  day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 1 AND 7), -- 1=Monday, 7=Sunday
  period_number INTEGER NOT NULL CHECK (period_number BETWEEN 1 AND 10),
  subject_id VARCHAR(64) REFERENCES subjects(id) ON DELETE SET NULL,
  subject_name VARCHAR(100), -- Denormalized for display
  
  -- Teacher info
  teacher_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Lesson details
  lesson_title VARCHAR(200) NOT NULL, -- Tên bài theo PPCT
  topic_code VARCHAR(50), -- Mã chủ đề/bài theo sách giáo khoa
  
  -- Attendance
  present_count INTEGER NOT NULL DEFAULT 0,
  absent_count INTEGER NOT NULL DEFAULT 0,
  absent_student_ids TEXT, -- JSON array of student IDs who were absent
  
  -- Lesson rating (TT22 style)
  score DECIMAL(4,2), -- 0-10 scale, NULL if not rated
  rating VARCHAR(16) CHECK (rating IN ('tot', 'kha', 'trung_binh', 'kem')),
  
  -- Notes
  notes TEXT, -- Nhận xét tiết học
  homework TEXT, -- Bài tập về nhà
  
  -- Digital signature
  teacher_signature VARCHAR(255), -- Timestamp + teacher name hash
  signed_at TIMESTAMPTZ,
  
  -- Status
  status VARCHAR(16) DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'approved')),
  approved_by VARCHAR(64) REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  
  -- Constraints
  UNIQUE (class_id, date, period_number, teacher_id)
);

CREATE INDEX IF NOT EXISTS idx_logbooks_class_date ON digital_class_logbooks(class_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_logbooks_teacher ON digital_class_logbooks(teacher_id);
CREATE INDEX IF NOT EXISTS idx_logbooks_school_date ON digital_class_logbooks(school_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_logbooks_academic_year ON digital_class_logbooks(academic_year, semester);
CREATE INDEX IF NOT EXISTS idx_logbooks_status ON digital_class_logbooks(status);

-- =============================================================================
-- STUDENT CONDUCT EVALUATIONS TABLE
-- TT22 Semester conduct grades with AI-suggested teacher comments
-- =============================================================================
CREATE TABLE IF NOT EXISTS student_conduct_evaluations (
  id VARCHAR(64) PRIMARY KEY,
  school_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(64) NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  class_id VARCHAR(64) NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  academic_year VARCHAR(32) NOT NULL,
  semester INTEGER NOT NULL CHECK (semester IN (1, 2, 0)), -- 0 = full year
  
  -- TT22 Conduct Rating
  conduct_grade VARCHAR(16) CHECK (conduct_grade IN ('tot', 'kha', 'dat', 'chua_dat')),
  
  -- Teacher comments (Học bạ)
  teacher_comment TEXT,
  ai_suggested_comment TEXT, -- Generated by AI before teacher edits
  
  -- Academic context for AI generation
  gpa DECIMAL(4,2), -- Điểm trung bình học tập
  attendance_rate DECIMAL(5,2), -- Tỷ lệ chuyên cần
  previous_conduct VARCHAR(16), -- Hạnh kiểm kỳ trước
  
  -- Metadata
  evaluation_type VARCHAR(16) DEFAULT 'semester' CHECK (evaluation_type IN ('midterm', 'semester', 'yearly')),
  
  -- Audit
  updated_by VARCHAR(64) REFERENCES users(id) ON DELETE SET NULL,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  
  -- Constraints
  UNIQUE (student_id, class_id, academic_year, semester, evaluation_type)
);

CREATE INDEX IF NOT EXISTS idx_conduct_student ON student_conduct_evaluations(student_id);
CREATE INDEX IF NOT EXISTS idx_conduct_class ON student_conduct_evaluations(class_id);
CREATE INDEX IF NOT EXISTS idx_conduct_academic ON student_conduct_evaluations(academic_year, semester);
CREATE INDEX IF NOT EXISTS idx_conduct_school ON student_conduct_evaluations(school_id);

-- =============================================================================
-- CLASS DISCIPLINE RECORDS TABLE
-- Tracks daily discipline violations reported by class monitors
-- Used for "Nề nếp & Thi đua 15 phút" feature
-- =============================================================================
CREATE TABLE IF NOT EXISTS class_discipline_records (
  id VARCHAR(64) PRIMARY KEY,
  school_id VARCHAR(64) NOT NULL,
  class_id VARCHAR(64) NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  group_id VARCHAR(64) REFERENCES class_groups(id) ON DELETE SET NULL, -- Tổ (Nhóm 1-4)
  
  -- Student involved
  student_id VARCHAR(64) NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  
  -- Date and period
  date DATE NOT NULL,
  period_number INTEGER CHECK (period_number BETWEEN 0 AND 12), -- 0 = 15-minute session
  
  -- Violation details
  violation_type VARCHAR(32) NOT NULL CHECK (violation_type IN (
    'uniform',      -- Đồng phục
    'late',         -- Đi muộn
    'no_homework',  -- Chưa học bài cũ
    'disruptive',   -- Mất trật tự
    'phone',        -- Sử dụng điện thoại
    'eating',       -- Ăn uống trong lớp
    'other'         -- Vi phạm khác
  )),
  points_deducted INTEGER NOT NULL DEFAULT -1, -- Points deducted from conduct
  
  -- Reporter (class monitor or group leader)
  reported_by VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Notes
  notes TEXT,
  
  -- Status
  status VARCHAR(16) DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'resolved', 'dismissed')),
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_discipline_class_date ON class_discipline_records(class_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_discipline_student ON class_discipline_records(student_id);
CREATE INDEX IF NOT EXISTS idx_discipline_group ON class_discipline_records(group_id);
CREATE INDEX IF NOT EXISTS idx_discipline_violation_type ON class_discipline_records(violation_type);
CREATE INDEX IF NOT EXISTS idx_discipline_status ON class_discipline_records(status);

-- =============================================================================
-- SEATING ARRANGEMENTS TABLE (Optional - for seating chart persistence)
-- =============================================================================
CREATE TABLE IF NOT EXISTS class_seating_arrangements (
  id VARCHAR(64) PRIMARY KEY,
  school_id VARCHAR(64) NOT NULL,
  class_id VARCHAR(64) NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  academic_year VARCHAR(32) NOT NULL,
  semester INTEGER CHECK (semester IN (1, 2, 0)),
  
  -- Grid configuration
  rows INTEGER NOT NULL DEFAULT 4,
  cols INTEGER NOT NULL DEFAULT 5,
  
  -- Seating data as JSON: { "A1": "student_id_1", "A2": null, ... }
  seating_data TEXT NOT NULL,
  
  -- Metadata
  description VARCHAR(200),
  is_active BOOLEAN DEFAULT TRUE,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  
  -- Constraints
  UNIQUE (class_id, academic_year, semester)
);

CREATE INDEX IF NOT EXISTS idx_seating_class ON class_seating_arrangements(class_id);

-- =============================================================================
-- MIGRATION COMPLETED
-- =============================================================================
